### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by jigar-sable** [jigar-sable/Android-Webview#2]
Update and Enhance the Readme File with - Better Description.

**Comment by BalajiG2000** [comment]
Can you assign this to me @jigar-sable

**Comment by BalajiG2000** [comment]
@jigar-sable  Can you assign this to me.

**Comment by dahiya-code** [comment]
I am from IITBHU
Please assign this to me

**Comment by Areeb786123** [comment]
plz assign me this
@jigar-sable

**Comment by dahiya-code** [comment]
thanks
